### ISSUE TITLE
Error on test shell file.

### ISSUE THREAD

**Issue by rafaelnovello** [italorossi/ishell#23]
When I run `python test_shell.py` I got the error below:

```
$ python test_shell.py 
Traceback (most recent call last):
  File "test_shell.py", line 2, in <module>
    from ishell.console import Console
  File "/home/rafael/prjs/ishell/ishell/console.py", line 6, in <module>
    from builtins import input
ImportError: No module named builtins
```
We need to install future to solve it, then it could be done at setup.py and/or requirements.txt

**Comment by italorossi** [comment]
Thank you, PR #24 merged.
